name: Azure Boards Work Item Link Verification
on:
  pull_request:
    types: [opened, reopened, edited, synchronize, enqueued, ready_for_review]

jobs:
  check-commit-message:
    name: Validate Work Item Link
    runs-on: windows-2019
    steps:
      - name: Check Work Item References
        shell: bash
        env:
          pr_title: ${{ github.event.pull_request.title }}
          pr_desc: ${{ github.event.pull_request.body }}
        run: |
          # Convert title and description to lowercase for case-insensitive matching
          title="${pr_title,,}"
          desc="${pr_desc,,}"

          # Check if either title or description contains a valid Azure Boards reference
          if [[ "$title" == *"fix [ab#"* || "$title" == *"fix ab#"* || "$title" == *"fixes [ab#"* || "$title" == *"fixes ab#"* || "$title" == *"fixed [ab#"* || "$title" == *"fixed ab#"* || "$title" == *"ab#"* ]] || 
             [[ "$desc" == *"fix [ab#"* || "$desc" == *"fix ab#"* || "$desc" == *"fixes [ab#"* || "$desc" == *"fixes ab#"* || "$desc" == *"fixed [ab#"* || "$desc" == *"fixed ab#"* || "$desc" == *"ab#"* ]]; then
              echo "PR Title or Description contains valid Azure Boards Work Item reference"
          else
              echo "Neither PR Title nor Description contains valid Azure Boards Work Item reference. Please use 'fixes AB#Work Item Number' or 'AB#Work Item Number' in either."
              exit 1
          fi
